# Site settings
author: Alyssa Brown
title: Coding Adventures/Misadventures
header-img: img/home-bg.png
email: alyssa.brown@live.com
copyright_name: Alyssa Brown
description: > # this means to ignore newlines until "baseurl:"
  my perspective 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alyssab444

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
